// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEZGLDx4zCKTKwlILhVl1QlrGQ_0QHEHo',
    appId: '1:848281107374:web:1bda6a14a451f0a630e63f',
    messagingSenderId: '848281107374',
    projectId: 'grill-corner-9a0da',
    authDomain: 'grill-corner-9a0da.firebaseapp.com',
    storageBucket: 'grill-corner-9a0da.firebasestorage.app',
    measurementId: 'G-QWV7P04D0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn5v4VqJzyAQeqkO01TJQmdd2kmufxgww',
    appId: '1:848281107374:android:43d688effe32f29b30e63f',
    messagingSenderId: '848281107374',
    projectId: 'grill-corner-9a0da',
    storageBucket: 'grill-corner-9a0da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVrQAy0hH57uigGPeyofT6kjUBx6h7bkg',
    appId: '1:848281107374:ios:7e16098b335610fe30e63f',
    messagingSenderId: '848281107374',
    projectId: 'grill-corner-9a0da',
    storageBucket: 'grill-corner-9a0da.firebasestorage.app',
    iosBundleId: 'com.example.eposPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVrQAy0hH57uigGPeyofT6kjUBx6h7bkg',
    appId: '1:848281107374:ios:7e16098b335610fe30e63f',
    messagingSenderId: '848281107374',
    projectId: 'grill-corner-9a0da',
    storageBucket: 'grill-corner-9a0da.firebasestorage.app',
    iosBundleId: 'com.example.eposPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEZGLDx4zCKTKwlILhVl1QlrGQ_0QHEHo',
    appId: '1:848281107374:web:85f2bbdb103a4fec30e63f',
    messagingSenderId: '848281107374',
    projectId: 'grill-corner-9a0da',
    authDomain: 'grill-corner-9a0da.firebaseapp.com',
    storageBucket: 'grill-corner-9a0da.firebasestorage.app',
    measurementId: 'G-RZNZ1VF6WB',
  );
}
